<a href="https://colab.research.google.com/github/MohitMhZn/AIML-TRAINING/blob/main/INTRODUCTION%20Numpy_5th__Sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#INTRO TO NUMPY

#what will we cover?


*  Creating single dimensional arrays✅
* multi dimnsional array
* randomly generated arrays
*  element wise operation
*   summarizing operations








## SINGLE DIMENSIONAL ARRAY


In [ ]:
import numpy as np


In [ ]:
#create an array with all the elements zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#create an array with all the elements one
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#create am array of size 10 with all element 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create an array with evenly spaced nummber within scified arange
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

##Multi dimensional arrray

In [ ]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a=np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0, 1] = 20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
a[2: 3] = 1
a

array([[1, 1, 1],
       [4, 5, 6],
       [1, 1, 1]])

In [ ]:
a[:, 2]= [2, 2, 2]
a

array([[2, 2, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [ ]:
np.full([3, 3], 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

### Randomly generated arrays



*   numpy can create arrays filled with random numbers
*   To ensure the reproductivility, you can set a seed ```np.random.seed()```. it will generate the exact same random numbers fir each executionss
*   if you remove or change the seed value the sequence of random humbers will be changes






In [ ]:
np.random.rand(5)

array([0.24804798, 0.84757659, 0.76588435, 0.0263034 , 0.37621859])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])